### ISSUE TITLE
建议添加Element客户端更换主服务器(homeserver)教程

### ISSUE THREAD

**Issue by Young-Lord** [unkoe/StartMatrixChatBook#2]
如题，这里提供一种不连接代理直接使用客户端的方法。同时建议给出[非官方的homeserver列表](https://joinmatrix.org/servers/)以供选择。
具体方式：
1. 运行一次Element，出现错误界面后退出
2. 在数据文件夹内新建文件`config.json`，编辑，更改为以下内容：
```json
{
    "default_server_config": {
        "m.homeserver": {
            "base_url": "https://matrix.EXAMPLE.com",
            "server_name": "EXAMPLE.com"
        }
    }
}
```
其中`EXAMPLE.com`需要更换为你使用的homeserver服务器地址（不需要大写），比如我的homeserver是`sibnsk.net`，我就需要将`EXAMPLE.com`改为`sibnsk.net`。这里的homeserver必须可以直连，且建议选择访问速度较好的。
3. 直接打开Element，正常出现登录页面即为成功。

---

（稍后可能会发一个pr）

**Comment by Young-Lord** [comment]
数据文件夹（Windows）：
原版：`%APPDATA%\Element`（也就是`C:\Users\用户名\AppData\Roaming\Element`）
[绿色版](https://portapps.io/app/element-portable/)：安装目录下的`data`文件夹

**Comment by unkoe** [comment]
欢迎PR

**Comment by Young-Lord** [comment]
您好，我在使用 Linux Python 3.11 本地运行时发生了如下 bug:
https://github.com/sphinx-doc/sphinx/issues/10378
根据 issue 中提到的方法已经可以正常构建，但这可能会破坏您那边的兼容，我稍后push上来你看看
以及，我需要在`requirements.txt`中加入`sphinx-rtd-theme`才可正常生成

你是不是应该把`git freeze`的输出写进`requirements.txt`中来防止版本不一致导致的问题？

**Comment by unkoe** [comment]
> 您好，我在使用 Linux Python 3.11 本地运行时发生了如下 bug: [sphinx-doc/sphinx#10378](https://github.com/sphinx-doc/sphinx/issues/10378) 根据 issue 中提到的方法已经可以正常构建，但这可能会破坏您那边的兼容，我稍后push上来你看看 以及，我需要在`requirements.txt`中加入`sphinx-rtd-theme`才可正常生成

因为换过了笔记本，这个问题我也无法复现，现在我也遇到了这个问题，可能是当时忘记了更新 requirements.txt。
> 
> 你是不是应该把`git freeze`的输出写进`requirements.txt`中来防止版本不一致导致的问题？

你的建议很不错。#4
